### ISSUE TITLE
What is the difference between https://github.com/pkgforge/soar? 

### ISSUE THREAD

**Issue by akkuman** [xplshn/dbin#12]
What is the difference between https://github.com/pkgforge/soar?

**Comment by xplshn** [comment]
> What is the difference between https://github.com/pkgforge/soar?

Soar does too much stuff for my liking, give it a try if you'd like I guess?
It does everything `dbin` does, but it has other stuff too (couldn't really say what that stuff is since soar is still WIP and the dev has been adding a lot of stuff, not all of which is documented. Currently, his pal, Ajam, is writting the docs for their infra and updating the `soar` cli docs too)

**Comment by akkuman** [comment]
LGTM，I will try https://github.com/xplshn/dbin

dbin uses Golang, I am more familiar with it

**Comment by xplshn** [comment]
> LGTM，I will try https://github.com/xplshn/dbin
> 
> dbin uses Golang, I am more familiar with it

If you're a Go dev, you're welcome to help with implementing a version of install.go/fetch.go that uses a parallel progressbar library for prettier output, I could not figure that out with https://github.com/hedzr/progressbar, the library behaved weirdly each time I tried to use it

**Comment by akkuman** [comment]
> 如果您是 Go 开发人员，欢迎您帮助实现 install.go/fetch.go 版本，该版本使用并行进度条库来获得更漂亮的输出，我无法通过[https://github.com](https://github.com/hedzr/progressbar)弄清楚这一点[/hedzr/progressbar](https://github.com/hedzr/progressbar) ，每次我尝试使用它时，库都表现得很奇怪

@xplshn What is the ultimate desired effect?

**Comment by xplshn** [comment]
> > 如果您是 Go 开发人员，欢迎您帮助实现 install.go/fetch.go 版本，该版本使用并行进度条库来获得更漂亮的输出，我无法通过[https://github.com](https://github.com/hedzr/progressbar)弄清楚这一点[/hedzr/progressbar](https://github.com/hedzr/progressbar) ，每次我尝试使用它时，库都表现得很奇怪
> 
> @xplshn What is the ultimate desired effect?

To have pretty progressbars when installing binaries, like those of `Pacman` (Arch's package manager)

by the way, if English isn't your native tongue, consider using a translator like "deepl", its pretty good

**Comment by xplshn** [comment]
Lovely, thanks very much!

**Comment by akkuman** [comment]
@xplshn https://github.com/xplshn/dbin/pull/13

**Comment by Azathothas** [comment]
Hi, @akkuman 
If you use telegram, come hang out with Us (@xplshn & rest of @pkgforge) at https://t.me/official_loonix/63954

**Comment by akkuman** [comment]
@Azathothas I will join this group.
