### ISSUE TITLE
List / index for installed packages.

### ISSUE THREAD

**Issue by lidgnulinux** [xplshn/dbin#20]
Hello, Is there a list or index of installed packages after we install package ? That would be useful for integrating with neofetch-like tool to show amount of dbin package.

**Comment by xplshn** [comment]
> Hello, Is there a list or index of installed packages after we install package ? That would be useful for integrating with neofetch-like tool to show amount of dbin package.

Yeah. `dbin info` without arguments will show all installed programs!
