### ISSUE TITLE
[Request] Relicense as open source?

### ISSUE THREAD

**Issue by imbev** [xplshn/dbin#22]
The current license for dbin is proprietary, rendering it less attractive to contribution and excluding it from inclusion in many software repositories.

I suggest that dbin relicense under an open source license. A license that is similar, but open source is the MIT license. Other licenses such as the MPL or the GPLv3 would also be sufficient to make this project open source.

**Comment by xplshn** [comment]
> The current license for dbin is proprietary

That's not true, a license is just an EULA, it can be however the author desires, and mine is perfectly legal in Argentina, and it also states that you can relicense as 3BSD if you want, I don't really care what harmful orgs like the OSI say

The source is open, the code is free, you can fork or even sell it if you want.

**Comment by imbev** [comment]
Can you show me where it states that dbin is also available under the 3BSD license?

**Comment by xplshn** [comment]
https://raw.githubusercontent.com/xplshn/dbin/refs/heads/master/LICENSE#:~:text=4.%20You%20can%20relicense%20under%20any%20license%20that%20meets%20the%20first%203%20conditions%20and%20isn't%20copylefted%2C%20as%20long%20as%20you%20aren't%20Richard%20M.%20Stallman.

The first 3 conditions are literally taken from the 3BSD license

Its also stated here:

https://github.com/xplshn/dbin#:~:text=dbin%20is%20licensed%20under%20the%20RABRMS%20License.%20This%20allows%20for%20the%20use%2C%20modification%2C%20and%20distribution%20of%20the%20software%20under%20certain%20conditions.%20For%20more%20details%2C%20please%20refer%20to%20the%20LICENSE%20file.%20This%20license%20is%20equivalent%20to%20the%20New%20or%20Revised%20BSD%20License.

**Comment by imbev** [comment]
Thank you

Would you mind a PR that adds the exact 3-Clause BSD License to the repo?

**Comment by xplshn** [comment]
No, sorry, its not planned.
I like my project this way.
I'll proceed to lock the issue now that misconceptions have been cleared up
