### ISSUE TITLE
No CLI output in response to any command

### ISSUE THREAD

**Issue by imbev** [xplshn/dbin#3]
Despite trying `--version`, `--help`, etc. I am not receiving any output to STDOUT.

e.g. The following command results in no output.

```bash
wget -qO- "https://raw.githubusercontent.com/xplshn/dbin/master/stubdl" | sh -s -- --help
```

Linux: 6.8.5
Glibc: 2.34

The system has a read-only root, but the home directory is mutable.

**Comment by xplshn** [comment]
I have just commited a fix. Would you mind trying again?

**Comment by xplshn** [comment]
![image](https://github.com/user-attachments/assets/6c282b57-aadd-4329-af69-4dec04d3aa0c)

**Comment by imbev** [comment]
It now works after installation, though the "non-install" usage command still shows no output.

**Comment by xplshn** [comment]
> It now works after installation, though the "non-install" usage command still shows no output.

That might be an issue with your shell. Would you mind showing me the output of these commands:
```
readlink /bin/sh
sh --help
```

Note that in order to use without installing, the `dbin` binary is downloaded to `/tmp`, therefore, it must be writable.

**Comment by xplshn** [comment]
I'm closing this for now. I tested with `ksh93`, `mksh`, `oksh`, `ash`, `dash`, and `bash`, and all of them worked.

**Comment by imbev** [comment]
I deleted `/tmp/._bdlstub_dbin.bin` and it worked. The installer didn't overwrite the older version.
