### ISSUE TITLE
A wildcard in place of app name when using del, will delete everything in the directory.

### ISSUE THREAD

**Issue by knotu** [xplshn/dbin#5]
First of all I wanted to say that I appreciate the project. Anyway, on to the issue. 

Command: dbin del *

I personally use ~/.local/bin which dbin defaults to. I backed it up and purposefully ran the command
above as a test and it deleted everything, including dbin.

Even if I'd change the default for dbin, I don't believe a wildcard should delete everything. Instead
it should provide a warning and if people want to actually delete all content in the directory, they
should be prompted to do it manually.

Thank you.

**Comment by xplshn** [comment]
`dbin` does not do that tho. Did you execute that command while in the $DBIN_INSTALL_DIR?
![image](https://github.com/user-attachments/assets/76fb3dfb-8da1-44f6-82b4-41cb69a5535d)

Unless a program explicitly handles the wildcard, what the shell will do is, pass every file & directory except '.' and '..' to the command being executed, some other programs may also be executed various times with the each file/directory as argument.

Here's proof of such behavior in a POSIX compliant shell (`ash`).
![image](https://github.com/user-attachments/assets/4c04cd8d-d8c5-44c1-902f-9decb932e0a5)
