### ISSUE TITLE
[Binary requests] xdo xdotool iotop-c mawk

### ISSUE THREAD

**Issue by Samueru-sama** [xplshn/dbin#7]
Those 4 binaries are the only ones that remain that I keep building or using my distro package manager to install or in the case of mawk, the aur.

**Comment by xplshn** [comment]
> Those 4 binaries are the only ones that remain that I keep building or using my distro package manager to install or in the case of mawk, the aur.

The binaries come from this repo: https://github.com/Azathothas/Toolpacks

Please make the request there :)

If you want to get rid of those ASAP, you can create a blob/appbundle of each of those, without adding the .blob/.AppBundle suffix, and eventually, if they're added to Toolpacks (the repo `dbin` uses), they will be replaced with a simple `dbin update`.

**Comment by xplshn** [comment]
Also, note that the `awk` in our repo is `onetrueawk`, by the original creators of the `awk` programming language.

**Comment by Samueru-sama** [comment]
>Please make the request there :)

Roger that.

>If you want to get rid of those ASAP, you can create a blob/appbundle of each of those, without adding the .blob/.AppBundle suffix, and eventually, if they're added to Toolpacks (the repo dbin uses), they will be replaced with a simple dbin update.

Wait, you are telling me that if I run a dbin update it will replace my existing binaries in my user bin dir?

>Also, note that the awk in our repo is onetrueawk, by the original creators of the awk programming language.

I like mawk because it is insanely fast, and I mean like I couldn't believe the times I was getting with it. 

This [simple script](https://github.com/Samueru-sama/dotfiles/blob/main/Local/scripts/polybar/getcpu.awk) took 500 us to get the info while a similar c++ binary took 1.2ms, though the difference eventually ended up being the dynamic linking in the c++ binary which after being removed managed to lower the time to 400 us but still, that was very impressive for an interpreted language.

**Comment by xplshn** [comment]
> Wait, you are telling me that if I run a dbin update it will replace my existing binaries in my user bin dir?

Yes, that's why `dbin` has a `$DBIN_INSTALL_DIR`... I have /opt/anto/dbin/bin and /opt/anto/dbin/dbin.tracker.json as places that my user can edit

**Comment by Azathothas** [comment]
Perhaps something similar to what used to exist over at hysp:
https://github.com/pwnwriter/hysp/issues/10
https://github.com/metis-os/hysp-pkgs/issues/3

It needn't be as detailed.
A more abridged shorter version to point people to the right repo or to this link: 
https://github.com/Azathothas/Toolpacks/tree/main/Docs#how-to-add-request-a-new-a-pkgtool
and pinned as an issue (or specified in the README) at this repo would be ideal.

**Comment by xplshn** [comment]
> Perhaps something similar to what used to exist over at hysp: [pwnwriter/hysp#10](https://github.com/pwnwriter/hysp/issues/10) [metis-os/hysp-pkgs#3](https://github.com/metis-os/hysp-pkgs/issues/3)
> 
> It needn't be as detailed. A more abridged shorter version to point people to the right repo or to this link: https://github.com/Azathothas/Toolpacks/tree/main/Docs#how-to-add-request-a-new-a-pkgtool and pinned as an issue (or specified in the README) at this repo would be ideal.

Done :)
THanks for the suggestion
