### ISSUE TITLE
[+] Hourly Metadata Update & Enforce Checksums

### ISSUE THREAD

**Issue by Azathothas** [xplshn/dbin#9]
I propose a new repo: `dbin-meta` or similar, and generate the metadata files there, every hr.
This way, this repo will avoid getting absurdly large and the `dbin-meta` can grow would have no such constraints. 
(You could also reset `dbin-meta` back to 1 commit, once the commit exceeds 10,000 etc)

Main reason, I add new pkgs almost every day, but bindl won't show it (search | info) until the bi-weekly update here.
Also, please consider validating and enforcing checksums. 
(If it's too bloaty, add a --verify or --check flag which will trigger the checksum check. This is a major feature missing from the original hysp. Hysp would perform checksum check after downloading the binary, would remove the binary immediately if it didn't match the checksums.)

It's not only for security, but also to ensure that binary wasn't half downloaded (due to network issues) etc.
And using stale metadata will often not match the checksums (or other dynamic value like size, build date), so this is another reason for `dbin-meta`

**Comment by xplshn** [comment]
>I propose a new repo: dbin-meta or similar, and generate the metadata files there, every hr.
>This way, this repo will avoid getting absurdly large and the dbin-meta can grow would have >no such constraints.
>(You could also reset dbin-meta back to 1 commit, once the commit exceeds 10,000 etc)
>
>Main reason, I add new pkgs almost every day, but bindl won't show it (search | info) until the bi-weekly update here.

Would you mind explaining how to set it up? Or setting it up yourself? I am not good with `git` and Github Actions/CI workflows at all.

> Also, please consider validating and enforcing checksums.
(If it's too bloaty, add a --verify or --check flag which will trigger the checksum check. This is a major feature missing from the original hysp. Hysp would perform checksum check after downloading the binary, would remove the binary immediately if it didn't match the checksums.)

> It's not only for security, but also to ensure that binary wasn't half downloaded (due to network issues) etc.
> And using stale metadata will often not match the checksums (or other dynamic value like size, build date), so this is another reason for dbin-meta

Will consider the implications of this. Good suggestion, probably can warn the user when the downloaded binary has no checksum field in its metadata, to keep `dbin` flexible.

**Comment by Azathothas** [comment]
> Would you mind explaining how to set it up? Or setting it up yourself? I am not good with git and Github Actions/CI workflows at all.

You just migrate the ["./misc/cmd/modMetadata"](https://github.com/xplshn/dbin/tree/master/misc/cmd/modMetadata) part to `dbin-meta` along with the ["./.github/workflows/modMetadata.yml"](https://github.com/xplshn/dbin/blob/master/.github/workflows/modMetadata.yml).
And change the cron to run every hr: `- cron: '0 * * * *`
If you need additional features like faster clones and auto resetting once commits reach a certain `N`, look into these:
```yaml
#Replace the checkout part with this
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
          filter: "blob:none"
          

#add this part right before the commit part (need only change the 1000, and username/email part)
      - name: Ensure Healthy Commit Nums (RESET ON >= 1000)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          pushd "$(mktemp -d)" > /dev/null 2>&1 && git clone --filter="blob:none" "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          cd "$(find . -maxdepth 1 -type d -exec basename {} \; | grep -Ev '^\.$' | xargs -I {} realpath {})"
          CLONED_DIR="$(realpath .)" && export CLONED_DIR="$CLONED_DIR"
          COMMIT_NUMS="$(git rev-list --count HEAD)" && export COMMIT_NUMS="$COMMIT_NUMS"
          popd > /dev/null 2>&1 ; rm -rf "$CLONED_DIR" 2>/dev/null
          cd "$GITHUB_WORKSPACE/main"
          if [ "$COMMIT_NUMS" -gt 1000 ]; then
              echo -e "\n[+] Total number of commits exceeds 1000. ($COMMIT_NUMS)\n"
              cd "$GITHUB_WORKSPACE/main"
              git config "user.name" "Your-Username"
              git config "user.email" "Your-email@gmail.com"
              git checkout --orphan temp
              git add --all --verbose && git commit -m "Purge (Re:Init)"
              git branch -D "main"
              git branch -m "main"
              git push --set-upstream origin main --force
              echo "RESET_HISTORY=YES" >> "$GITHUB_ENV"
          else
              echo -e "\n[+] Total number of commits looks healthy. ($COMMIT_NUMS)\n"
              echo "RESET_HISTORY=NO" >> "$GITHUB_ENV"
          fi
          pushd "$GITHUB_WORKSPACE/main" >/dev/null 2>&1 && git pull origin main && popd >/dev/null 2>&1
        continue-on-error: true                  
```
If you need more ~abominations~ tips & tricks look into : https://github.com/Azathothas/Toolpacks/blob/main/.github/workflows/healthchecks_housekeeping.yaml

And then you just change some links on this repo to use `dbin-meta`.

**Comment by xplshn** [comment]
Oh! Thanks! You didn't have to go so far, but I appreciate it, I'll try to set it up either today or tomorrow

**Comment by xplshn** [comment]
Wait, on a second thought. Wouldn't it make more sense if Toolpacks ran modMetadata after generating the normal metadata? (all modMetadata does is convert extra_ fields to directories, so that suites like coreutils/ and busybox/ appear on the search.)

**Comment by xplshn** [comment]
I can modify modMetadata to receive files, instead of downloading them.

**Comment by Azathothas** [comment]
If we always agreed there would be no need to have a separate metadata at all.
So it's best you do it on your own account and access.

**Comment by xplshn** [comment]
> If we always agreed there would be no need to have a separate metadata at all. So it's best you do it on your own account and access.

Its not that we disagree, your only reason for not adding entries for binaries in subdirectories was compability with existing projects reliant on Toolpacks. BTW, that could be solved if subdirectories included their own METADATA.json, just like `binutils` has, I can even write a go program to do that for you.

Also, I am only asking that you execute modMetadata so that .dbin.json files are also made available through the Toolpacks repo, I am not asking that you replace your current way of doing things. (even if I think it would be desirable to have entries for binaries in subdirectories.)

**Comment by Azathothas** [comment]
> even if I think it would be desirable to have entries for binaries in subdirectories.

They are already in the main metadata. But not in the $ARCH metadata, and I think that's what you mean.

> execute modMetadata so that .dbin.json files are also made available through the Toolpacks repo

We had a separate hysp-pkgs repo for hysp, because we found out that having a dedicated metadata repo is much simpler, easier to manage in the long run.
I already have countless metadata files (yaml & json) along with lots of scripts in the toolpacks. It's already a lot to maintain them.
I don't think adding dbin on top of that load is going to help me.

And in the future there might be disagreements, like there already is now, and I would like to avoid a nasty situation.
So please consider doing this on your own account.
I am willing to help write workflows if that's what is holding you back.

**Comment by xplshn** [comment]
> They are already in the main metadata. But not in the $ARCH metadata, and I think that's what you mean.

The only reason I am not using the ROOT METADATA.json is because it is just too slow, even with a faster, SIMD, encoding/json library, maybe the JSON could be minified, but it may not help that much, as the parsing would still be slow.

BTW, I'll try to make downloads parallel in the future.

> I am willing to help write workflows if that's what is holding you back.

Can I add you as a contributor to `dbin-meta` after I create such repo? I am willing to give it a try myself, its just that yaml gives me headaches, I wish I was able to use another format, yaml makes me SUFFER.

**Comment by Azathothas** [comment]
Create the initial repo and this, I don't think you would need my help at all but sure, I could fix the workflows if it errors out

> > Would you mind explaining how to set it up? Or setting it up yourself? I am not good with git and Github Actions/CI workflows at all.
> 
> You just migrate the ["./misc/cmd/modMetadata"](https://github.com/xplshn/dbin/tree/master/misc/cmd/modMetadata) part to `dbin-meta` along with the ["./.github/workflows/modMetadata.yml"](https://github.com/xplshn/dbin/blob/master/.github/workflows/modMetadata.yml). And change the cron to run every hr: `- cron: '0 * * * *` If you need additional features like faster clones and auto resetting once commits reach a certain `N`, look into these:
> 
> ```yaml
> #Replace the checkout part with this
>       - name: Checkout repository
>         uses: actions/checkout@v4
>         with:
>           path: main
>           filter: "blob:none"
>           
> 
> #add this part right before the commit part (need only change the 1000, and username/email part)
>       - name: Ensure Healthy Commit Nums (RESET ON >= 1000)
>         run: |
>           #Presets
>           set +x ; set +e
>           #--------------#
>           pushd "$(mktemp -d)" > /dev/null 2>&1 && git clone --filter="blob:none" "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
>           cd "$(find . -maxdepth 1 -type d -exec basename {} \; | grep -Ev '^\.$' | xargs -I {} realpath {})"
>           CLONED_DIR="$(realpath .)" && export CLONED_DIR="$CLONED_DIR"
>           COMMIT_NUMS="$(git rev-list --count HEAD)" && export COMMIT_NUMS="$COMMIT_NUMS"
>           popd > /dev/null 2>&1 ; rm -rf "$CLONED_DIR" 2>/dev/null
>           cd "$GITHUB_WORKSPACE/main"
>           if [ "$COMMIT_NUMS" -gt 1000 ]; then
>               echo -e "\n[+] Total number of commits exceeds 1000. ($COMMIT_NUMS)\n"
>               cd "$GITHUB_WORKSPACE/main"
>               git config "user.name" "Your-Username"
>               git config "user.email" "Your-email@gmail.com"
>               git checkout --orphan temp
>               git add --all --verbose && git commit -m "Purge (Re:Init)"
>               git branch -D "main"
>               git branch -m "main"
>               git push --set-upstream origin main --force
>               echo "RESET_HISTORY=YES" >> "$GITHUB_ENV"
>           else
>               echo -e "\n[+] Total number of commits looks healthy. ($COMMIT_NUMS)\n"
>               echo "RESET_HISTORY=NO" >> "$GITHUB_ENV"
>           fi
>           pushd "$GITHUB_WORKSPACE/main" >/dev/null 2>&1 && git pull origin main && popd >/dev/null 2>&1
>         continue-on-error: true                  
> ```
> 
> If you need more ~abominations~ tips & tricks look into : https://github.com/Azathothas/Toolpacks/blob/main/.github/workflows/healthchecks_housekeeping.yaml
> 
> And then you just change some links on this repo to use `dbin-meta`.

**Comment by xplshn** [comment]
![image](https://github.com/user-attachments/assets/6ae70858-beb7-48b0-80e4-804e246955b4)

What? It fails at 'name' of all things?

**Comment by Azathothas** [comment]
no worries, I will fix it

**Comment by Azathothas** [comment]
It's done at: [![🐧🧬 Generate Metadata 🖳🧬](https://github.com/xplshn/dbin-metadata/actions/workflows/gen_update_metadata.yml/badge.svg)](https://github.com/xplshn/dbin-metadata/actions/workflows/gen_update_metadata.yml)
Also linked a PR: https://github.com/xplshn/dbin/pull/10

Could close this now, but probably should leave open for you to implement the checksum checks

**Comment by xplshn** [comment]
> It's done at: [![🐧🧬 Generate Metadata 🖳🧬](https://github.com/xplshn/dbin-metadata/actions/workflows/gen_update_metadata.yml/badge.svg)](https://github.com/xplshn/dbin-metadata/actions/workflows/gen_update_metadata.yml) Also linked a PR: #10
> 
> Could close this now, but probably should leave open for you to implement the checksum checks

Done. Checksums are now checked. Still W.I.P, I am not sure if it works. It'd be great if you could provide a _internal.test directory in the repo to test various things? For now I mean...

**Comment by Azathothas** [comment]
_internal.test directory?
Which repo?

**Comment by xplshn** [comment]
Toolpacks, if possible. _internal.test/* could contain the following:
- Binary with checksum that does not match
- Binary with broken name element
- Binary of size 0

and anything you wish to test as well

**Comment by Azathothas** [comment]
You could just edit the metadata json from dbin-metadata repo.
Change the checksums and such, and try.
You will have one hr until.the workflow runs again and overwrite the changes, but you can test

**Comment by Azathothas** [comment]
Binary of size 0 isn't possible, it won't even show up in the bucket

**Comment by xplshn** [comment]
> Binary of size 0 isn't possible, it won't even show up in the bucket

`touch ./myWreckedBinary`?

**Comment by Azathothas** [comment]
Nope, I deliberately added a sanity check to not show certain things in the dir listing and in metadata.
This is the reason why you don't see upx binaries despite them existing.
The filter excludes (deletes) 0 byte sized objects, empty directories and file formats like .PNG .xml etc.
And it hides things like .upx

I would have to redeploy and build the node app from scratch.
It's too much work just to test a 0 sized binary.


Also, you can just edit the metadata,
Point the download url to a GitHub hosted file (that's 0 byte).
It's not necessary to use only my bucket/repos

**Comment by xplshn** [comment]
> Nope, I deliberately added a sanity check to not show certain things in the dir listing and in metadata. This is the reason why you don't see upx binaries despite them existing. The filter excludes (deletes) 0 byte sized objects, empty directories and file formats like .PNG .xml etc. And it hides things like .upx
> 
> I would have to redeploy and build the node app from scratch. It's too much work just to test a 0 sized binary.
> 
> Also, you can just edit the metadata, Point the download url to a GitHub hosted file (that's 0 byte). It's not necessary to use only my bucket/repos

You're right...
